# Site settings
title: TransHarbor
email: contact@transharbor.org
description: >-
  TransHarbor is a community owned and governed platform built by trans and nonbinary people, for trans and nonbinary people worldwide.
baseurl: ""
url: "https://transharbor.org"

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Navigation
header_pages:
  - about.md
  - mission.md
  - safety.md
  - community.md
  - deirdre.md

# Social links
minima:
  social_links:
    github: transharbor-org

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - README.md
  - LICENSE