# Site settings
title: TransHarbor
email: contact@transharbor.org
description: >-
  TransHarbor is a collectively owned and democratically governed community platform dedicated to serving the trans and nonbinary community.
baseurl: ""
url: "https://transharbor.org"

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Navigation
header_pages:
  - about.md
  - guidelines.md
  - governance.md

# Social links
minima:
  social_links:
    github: transharbor-org

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - README.md
  - LICENSE